name: minds2market
favicon: null
layout_spectrum: 0.5104395500384271
typography_spectrum: 0.4017795817926526
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8531821356154978
  lightness: 0.2689179414883256
  saturation: 0.9506528300698847
  rhythmicContrast: 0.07980649988166988
purpose: []
